version: "3"
services:
    node:
        image: node:10
        env_file: .env
        ports:
            - "8080:8080"
        depends_on:
            - mongo
        links:
            - mongo
        volumes:
            - ./app:/usr/src/app
        working_dir: /usr/src/app
        command: ["node", "index.js"]
    mongo:
        image: mongo
        env_file: .env
        volumes:
            - ./data/db:/data/db
